platform :ios, '14.0'

use_frameworks!

target 'App' do
  # Add Capacitor dependencies
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

  # Additional dependencies (if any)
end
